<#
.SYNOPSIS
  Generate data\.env for a standalone TK Comms Sentinel install.

.DESCRIPTION
  Writes the environment file the backend reads at startup: HTTPS port, TLS
  certificate paths, database path, and freshly generated random JWT secrets.
  LDAP and SMTP are left empty (local admin auth works out of the box; the
  operator fills these in later via Admin > Settings or by editing .env).

  Lives in data\, not backend\: in the versioned install layout, backend\ is
  inside versions\x.y.z\ (replaced on every update) while data\ is shared and
  never touched by an update. The running service finds it via the
  TKCS_DATA_DIR environment variable that svc-install.ps1 sets (server.js and
  poller-service.js fall back to their own directory when that variable is
  not set, e.g. a pre-versioned flat install).

  Refuses to overwrite an existing .env unless -Force is given, so re-running
  never silently rotates the JWT secret (which would invalidate live sessions).

  ASCII-only, and the file is written without a BOM so dotenv parses the first
  key correctly.

  PFX credentials: pass -PfxInfoFile pointing at the pfx-info.env written by
  new-selfsigned-cert.ps1 (its default output path is <Root>\data\certs\
  pfx-info.env) and this script reads PFX_PATH/PFX_PASSWORD from that file
  directly. Prefer this over passing -PfxPath/-PfxPassword from a captured
  variable: capturing a script's console output ("$x = & script.ps1 ...")
  proved unreliable in the field and produced an empty TLS_PFX_PASSWORD in a
  real install. Reading a file the other script wrote itself has no such
  failure mode.
#>
[CmdletBinding()]
param(
  [string] $Root        = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
  [int]    $HttpsPort   = 9443,
  [string] $PfxInfoFile = '',
  [string] $PfxPath     = '',
  [string] $PfxPassword = '',
  [string] $CertPath    = '',
  [string] $KeyPath     = '',
  [string] $DbPath      = '',
  [string] $AppBaseUrl  = '',
  [switch] $Force
)

$ErrorActionPreference = 'Stop'

$dataDir = Join-Path $Root 'data'
if (-not (Test-Path -LiteralPath $dataDir)) { New-Item -ItemType Directory -Path $dataDir -Force | Out-Null }
$envPath = Join-Path $dataDir '.env'

if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  throw ".env already exists: $envPath  (use -Force to overwrite)"
}

# Preferred path: read PFX credentials from the file new-selfsigned-cert.ps1
# wrote itself (see PfxInfoFile default below and the .DESCRIPTION note).
if (-not $PfxInfoFile -and -not $PfxPath -and -not $CertPath) {
  $PfxInfoFile = Join-Path $Root 'data\certs\pfx-info.env'
}
if ($PfxInfoFile) {
  if (-not (Test-Path -LiteralPath $PfxInfoFile)) { throw "PFX info file not found: $PfxInfoFile" }
  $info = @{}
  foreach ($line in Get-Content -LiteralPath $PfxInfoFile) {
    if ($line -match '^([^=]+)=(.*)$') { $info[$matches[1]] = $matches[2] }
  }
  if (-not $info.ContainsKey('PFX_PATH') -or -not $info.ContainsKey('PFX_PASSWORD')) {
    throw "PFX info file missing PFX_PATH/PFX_PASSWORD: $PfxInfoFile"
  }
  $PfxPath     = $info['PFX_PATH']
  $PfxPassword = $info['PFX_PASSWORD']
}

# Defaults derived from Root / machine name.
if (-not $PfxPath -and -not $CertPath) { $PfxPath = Join-Path $Root 'data\certs\server.pfx' }
if (-not $DbPath)     { $DbPath     = Join-Path $Root 'data\netmonitor.db' }
if (-not $AppBaseUrl) { $AppBaseUrl = "https://$($env:COMPUTERNAME):$HttpsPort" }

if ($PfxPath -and -not $PfxPassword) {
  throw "PfxPath is set but PfxPassword is empty -- refusing to write a .env with an unusable cert. Pass -PfxInfoFile instead of -PfxPath/-PfxPassword by hand."
}

function New-Secret {
  # 64 hex chars = 256 bits.
  -join (1..64 | ForEach-Object { '{0:x}' -f (Get-Random -Maximum 16) })
}

$lines = @(
  '# Generated by write-env.ps1 - standalone TK Comms Sentinel'
  'NODE_ENV=production'
  "HTTPS_PORT=$HttpsPort"
  'PORT=3001'
)
if ($PfxPath)  { $lines += "TLS_PFX_PATH=$PfxPath"; $lines += "TLS_PFX_PASSWORD=$PfxPassword" }
if ($CertPath) { $lines += "TLS_CERT_PATH=$CertPath"; $lines += "TLS_KEY_PATH=$KeyPath" }
$lines += @(
  "DB_PATH=$DbPath"
  "APP_BASE_URL=$AppBaseUrl"
  "JWT_SECRET=$(New-Secret)"
  "JWT_TEMP_SECRET=$(New-Secret)"
  'DEMO_MODE=false'
  'DEFAULT_SNMP_COMMUNITY=public'
  'SNMP_TIMEOUT_MS=5000'
  ''
  '# LDAP / Active Directory (leave empty for local auth only)'
  'LDAP_URL='
  'LDAP_BASE_DN='
  'LDAP_BIND_DN='
  'LDAP_BIND_PASSWORD='
  'LDAP_CA_CERT='
  'AD_ADMIN_GROUP=NetMonitor_Admins'
  'AD_VIEWER_GROUP=NetMonitor_Viewers'
  ''
  '# SMTP (leave SMTP_HOST empty to disable email alerts)'
  'SMTP_HOST='
  'SMTP_PORT=25'
  'SMTP_FROM='
  'ALERT_RECIPIENTS='
  ''
  'CLAUDE_API_KEY='
)

# Write without BOM (dotenv chokes on a BOM before the first key).
$text = ($lines -join "`r`n") + "`r`n"
[System.IO.File]::WriteAllText($envPath, $text, (New-Object System.Text.ASCIIEncoding))

Write-Host "[env] Wrote $envPath"
Write-Host "[env] HTTPS_PORT=$HttpsPort  DB_PATH=$DbPath"
Write-Host "[env] APP_BASE_URL=$AppBaseUrl"
if ($PfxPath)  { Write-Host "[env] TLS: PFX $PfxPath" }
if ($CertPath) { Write-Host "[env] TLS: PEM $CertPath" }
Write-Host "[env] JWT secrets generated (256-bit)."
