<#
.SYNOPSIS
  Generate backend\.env for a standalone TK Comms Sentinel install.

.DESCRIPTION
  Writes the environment file the backend reads at startup: HTTPS port, TLS
  certificate paths, database path, and freshly generated random JWT secrets.
  LDAP and SMTP are left empty (local admin auth works out of the box; the
  operator fills these in later via Admin > Settings or by editing .env).

  Refuses to overwrite an existing .env unless -Force is given, so re-running
  never silently rotates the JWT secret (which would invalidate live sessions).

  ASCII-only, and the file is written without a BOM so dotenv parses the first
  key correctly.
#>
[CmdletBinding()]
param(
  [string] $Root        = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
  [int]    $HttpsPort   = 9443,
  [string] $PfxPath     = '',
  [string] $PfxPassword = '',
  [string] $CertPath    = '',
  [string] $KeyPath     = '',
  [string] $DbPath      = '',
  [string] $AppBaseUrl  = '',
  [switch] $Force
)

$ErrorActionPreference = 'Stop'

$backendDir = Join-Path $Root 'backend'
if (-not (Test-Path -LiteralPath $backendDir)) { throw "backend directory not found: $backendDir" }
$envPath = Join-Path $backendDir '.env'

if ((Test-Path -LiteralPath $envPath) -and -not $Force) {
  throw ".env already exists: $envPath  (use -Force to overwrite)"
}

# Defaults derived from Root / machine name.
if (-not $PfxPath -and -not $CertPath) { $PfxPath = Join-Path $Root 'data\certs\server.pfx' }
if (-not $DbPath)     { $DbPath     = Join-Path $Root 'data\netmonitor.db' }
if (-not $AppBaseUrl) { $AppBaseUrl = "https://$($env:COMPUTERNAME):$HttpsPort" }

function New-Secret {
  # 64 hex chars = 256 bits.
  -join (1..64 | ForEach-Object { '{0:x}' -f (Get-Random -Maximum 16) })
}

$lines = @(
  '# Generated by write-env.ps1 - standalone TK Comms Sentinel'
  'NODE_ENV=production'
  "HTTPS_PORT=$HttpsPort"
  'PORT=3001'
)
if ($PfxPath)  { $lines += "TLS_PFX_PATH=$PfxPath"; $lines += "TLS_PFX_PASSWORD=$PfxPassword" }
if ($CertPath) { $lines += "TLS_CERT_PATH=$CertPath"; $lines += "TLS_KEY_PATH=$KeyPath" }
$lines += @(
  "DB_PATH=$DbPath"
  "APP_BASE_URL=$AppBaseUrl"
  "JWT_SECRET=$(New-Secret)"
  "JWT_TEMP_SECRET=$(New-Secret)"
  'DEMO_MODE=false'
  'DEFAULT_SNMP_COMMUNITY=public'
  'SNMP_TIMEOUT_MS=5000'
  ''
  '# LDAP / Active Directory (leave empty for local auth only)'
  'LDAP_URL='
  'LDAP_BASE_DN='
  'LDAP_BIND_DN='
  'LDAP_BIND_PASSWORD='
  'LDAP_CA_CERT='
  'AD_ADMIN_GROUP=NetMonitor_Admins'
  'AD_VIEWER_GROUP=NetMonitor_Viewers'
  ''
  '# SMTP (leave SMTP_HOST empty to disable email alerts)'
  'SMTP_HOST='
  'SMTP_PORT=25'
  'SMTP_FROM='
  'ALERT_RECIPIENTS='
  ''
  'CLAUDE_API_KEY='
)

# Write without BOM (dotenv chokes on a BOM before the first key).
$text = ($lines -join "`r`n") + "`r`n"
[System.IO.File]::WriteAllText($envPath, $text, (New-Object System.Text.ASCIIEncoding))

Write-Host "[env] Wrote $envPath"
Write-Host "[env] HTTPS_PORT=$HttpsPort  DB_PATH=$DbPath"
Write-Host "[env] APP_BASE_URL=$AppBaseUrl"
if ($PfxPath)  { Write-Host "[env] TLS: PFX $PfxPath" }
if ($CertPath) { Write-Host "[env] TLS: PEM $CertPath" }
Write-Host "[env] JWT secrets generated (256-bit)."
